#!/bin/sh

# Install script for lib_java_seqrecord
# In development mode does nothing, otherwise compiles source into a temp
# directory, jars the .class files to $INSTALLDIR, removes the temp directories
#
# This script must be run from the directory in which it resides (the top
# level of the lib_java_seqrecord installation)
#
# exit codes:
#	3 = improper command line usage
#	4 = $INSTALLDIR does not exist

# parameters:
# 	use param 'fordev' to install for development - basically do nothing 
# 	use param 'INSTALLDIR' to specify dir under which to create jar file
# 	use no param to create jar file under default INSTALLDIR
USAGE="Usage: $0 [fordev | INSTALLDIR]\n"

# param name to install for development
FORDEV=fordev

# default path to the jar file installation directory
INSTALLDIR=/usr/local/mgi/lib/java

# full path to the source installation directory
TOP=`pwd`

# temp dir to create
TEMPDIR=$TOP/temp

# lib_java_seqrecord package hierarchy where .class files will be created
PACKAGEDIR=org/jax/mgi/bio/seqrecord

# if we have more then one parameter echo usage
if [ $# -gt 1 ]
then
        echo $USAGE
	exit 3
fi

# if we have the 'fordev' parameter we install for development
if [ $# -eq 1 ] 
then
 	if [ $1 = $FORDEV ]
	then
		# don't do anything
		exit 0
	else 
	 	# assume alternate install path
		INSTALLDIR=$1
	fi	
fi

# install for real
# check INSTALLDIR
if [ ! -d $INSTALLDIR ]
then
	echo "$INSTALLDIR is not a directory"
	exit 4
fi

cd $TOP
# create a temp dir - mkdir $TOP/temp
if [ ! -d $TEMPDIR ]
then
	mkdir $TEMPDIR
fi

# compile source files
cd src
javac -d $TEMPDIR *.java

# create jar file under $INSTALLDIR
cd $TEMPDIR
jar cvf $INSTALLDIR/seqrecord.jar $PACKAGEDIR/*.class
 
# remove temp directory
cd $TOP
rm -rf $TEMPDIR 

